name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_DOCKER_PASS }} | docker login --username=${{ secrets.ACR_DOCKER_USER }} --password-stdin crpi-rzhzrny326es98fs.cn-hangzhou.personal.cr.aliyuncs.com

      - name: Build and Push
        run: |
          docker build -t registry.cn-hangzhou.aliyuncs.com/xbbwa/obsidian:latest .
          docker push registry.cn-hangzhou.aliyuncs.com/xbbwa/obsidian:latest
